version: "3"
services:
  episen-sca-lbe-back:
    image: back
    ports:
      - "8080"
    volumes:
      - ./log
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 300M
        reservations:
          cpus: "0.5"
          memory: 200M
      restart_policy:
        condition: on-failure

  episen-sca-lbe-front:
    image: louisbeaudin/episen-sca-lbe-front
    ports:
      - "80"
    volumes:
      - ./logfront
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost:80"]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
