version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.5"
          memory: 100M
